### ISSUE TITLE
Build failed with segfault during ttl generation for Dexed

### ISSUE THREAD

**Issue by ycollet** [DISTRHO/DISTRHO-Ports#21]
I build DISTRHO on Fedora 24 from git repo.
During the build, I met the following problem:

```
Generate ttl data for './Dexed.so', basename: 'Dexed'
./scripts/generate-ttl.sh : ligne 27 : 14735 Segmentation fault      (core dumped)$GEN ./$FILE
Makefile:59 : la recette pour la cible « gen_lv2 » a échouée
make[1]: *** [gen_lv2] Erreur 139
make[1] : on quitte le répertoire « /home/collette/repositories/DISTRHO-Ports »
Makefile:10 : la recette pour la cible « all » a échouée
make: *** [all] Erreur 2
```

**Comment by ycollet** [comment]
I finally managed to have a gdb trace:
```
$ gdb --args libs/lv2_ttl_generator bin/lv2/Dexed.lv2/Dexed_debug.so    
GNU gdb (GDB) Fedora 7.11.1-86.fc24
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from libs/lv2_ttl_generator...done.
(gdb) r
Starting program: /home/collette/repositories/DISTRHO-Ports/libs/lv2_ttl_generator bin/lv2/Dexed.lv2/Dexed_debug.so
Missing separate debuginfos, use: dnf debuginfo-install glibc-2.23.1-12.fc24.x86_64
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Generate ttl data for 'bin/lv2/Dexed.lv2/Dexed_debug.so', basename: 'Dexed_debug'

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff64462f2 in juce::(anonymous namespace)::AlsaClient::AlsaClient (this=0x637800) at ../source/modules/juce_audio_devices/native/juce_linux_Midi.cpp:276
276             snd_seq_set_client_name (handle, JUCE_ALSA_MIDI_NAME);
Missing separate debuginfos, use: dnf debuginfo-install alsa-lib-1.1.1-1.fc24.x86_64 bzip2-libs-1.0.6-21.fc24.x86_64 freetype-freeworld-2.6.3-4.fc24.x86_64 libX11-1.6.3-3.fc24.x86_64 libXau-1.0.8-6.fc24.x86_64 libXext-1.3.3-4.fc24.x86_64 libgcc-6.3.1-1.fc24.x86_64 libpng-1.6.27-1.fc24.x86_64 libstdc++-6.3.1-1.fc24.x86_64 libxcb-1.11.1-2.fc24.x86_64 zlib-1.2.8-10.fc24.x86_64
(gdb) where
#0  0x00007ffff64462f2 in juce::(anonymous namespace)::AlsaClient::AlsaClient (this=0x637800) at ../source/modules/juce_audio_devices/native/juce_linux_Midi.cpp:276
#1  0x00007ffff6445e61 in juce::(anonymous namespace)::AlsaClient::getInstance () at ../source/modules/juce_audio_devices/native/juce_linux_Midi.cpp:202
#2  0x00007ffff6446b0b in juce::(anonymous namespace)::iterateMidiDevices (forInput=true, deviceNamesFound=..., deviceIndexToOpen=-1)
    at ../source/modules/juce_audio_devices/native/juce_linux_Midi.cpp:418
#3  0x00007ffff64471f7 in juce::MidiInput::getDevices () at ../source/modules/juce_audio_devices/native/juce_linux_Midi.cpp:550
#4  0x00007ffff63b3b18 in SysexComm::setInput (this=0x61ee20, target=...) at ../source/SysexComm.cpp:62
#5  0x00007ffff63cc7c3 in DexedAudioProcessor::loadPreference (this=0x61bf50) at ../source/PluginParam.cpp:694
#6  0x00007ffff63e35c9 in DexedAudioProcessor::DexedAudioProcessor (this=0x61bf50) at ../source/PluginProcessor.cpp:75
#7  0x00007ffff63e4853 in createPluginFilter () at ../source/PluginProcessor.cpp:252
#8  0x00007ffff63ed426 in createPluginFilterOfType (type=juce::AudioProcessor::wrapperType_LV2)
    at ../../../libs/juce/source/modules/juce_audio_plugin_client/utility/juce_PluginUtilities.cpp:165
#9  0x00007ffff63ecc1b in createLv2Files (basename=0x7fffffffd940 "Dexed_debug")
    at ../../../libs/juce/source/modules/juce_audio_plugin_client/LV2/juce_LV2_Wrapper.cpp:507
#10 0x00007ffff63ed3be in lv2_generate_ttl (basename=0x7fffffffd940 "Dexed_debug")
    at ../../../libs/juce/source/modules/juce_audio_plugin_client/LV2/juce_LV2_Wrapper.cpp:2147
#11 0x0000000000400a15 in main (argc=2, argv=0x7fffffffdac8) at lv2_ttl_generator.cpp:69
(gdb) 
```

**Comment by ycollet** [comment]
And the listing at the segfault:
```
(gdb) list
271         {
272             jassert (instance == nullptr);
273
274             snd_seq_open (&handle, "default", SND_SEQ_OPEN_DUPLEX, 0);
275             snd_seq_nonblock (handle, SND_SEQ_NONBLOCK);
276             snd_seq_set_client_name (handle, JUCE_ALSA_MIDI_NAME);
277             clientId = snd_seq_client_id(handle);
278
279             // It's good idea to pre-allocate a good number of elements
280             ports.ensureStorageAllocated (32);
```

**Comment by falkTX** [comment]
I think it might be fixed now, please test.
Thank you.

**Comment by ycollet** [comment]
Thanks, it works fine now. 
I close the issue
