### ISSUE TITLE
crash with vitalium LV2 when reopening the UI

### ISSUE THREAD

**Issue by alex-tee** [DISTRHO/DISTRHO-Ports#79]
UI crashes when re-opening (after closing it once)

this also happens if I resize the UI before closing it

apitrace output here: www.zrythm.org/downloads/zrythm.trace.tar.xz 

```
JUCE Assertion failure in juce_OpenGLShaderProgram.cpp:138
--Type <RET> for more, q to quit, c to continue without paging--

Thread 34 "Pool" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fff9501c640 (LWP 1004615)]
0x00007fffb86d73f0 in ?? ()
(gdb) bt
#0  0x00007fffb86d73f0 in  ()
#1  0x00007fff9675485a in juce::OpenGLShaderProgram::use() const (this=0x7fffb862d430) at ../libs/juce-current/source/modules/juce_opengl/opengl/juce_OpenGLShaderProgram.cpp:140
#2  0x00007fff9652a3aa in OpenGlMultiQuad::render(OpenGlWrapper&, bool) (this=0x55558f440c68, open_gl=..., animate=true) at ../ports/vitalium/source/interface/editor_components/open_gl_multi_quad.cpp:143
#3  0x00007fff9653a3e7 in MidiKeyboard::render(OpenGlWrapper&, bool) (this=0x55558f4405b0, open_gl=..., animate=true) at ../ports/vitalium/source/interface/editor_components/midi_keyboard.cpp:203
#4  0x00007fff96593eff in SynthSection::renderOpenGlComponents(OpenGlWrapper&, bool) (this=0x55558ee71ca0, open_gl=..., animate=true) at ../ports/vitalium/source/interface/editor_sections/synth_section.cpp:381
#5  0x00007fff96593e30 in SynthSection::renderOpenGlComponents(OpenGlWrapper&, bool) (this=0x555587a6f180, open_gl=..., animate=true) at ../ports/vitalium/source/interface/editor_sections/synth_section.cpp:376
#6  0x00007fff963e4376 in FullInterface::renderOpenGL() (this=0x555587a6f180) at ../ports/vitalium/source/interface/editor_sections/full_interface.cpp:562
#7  0x00007fff9675f410 in juce::OpenGLContext::CachedImage::renderFrame() (this=0x555590da5000) at ../libs/juce-current/source/modules/juce_opengl/opengl/juce_OpenGLContext.cpp:255
#8  0x00007fff9675fded in juce::OpenGLContext::CachedImage::runJob() (this=0x555590da5000) at ../libs/juce-current/source/modules/juce_opengl/opengl/juce_OpenGLContext.cpp:486
#9  0x00007fff95a3884f in juce::ThreadPool::runNextJob(juce::ThreadPool::ThreadPoolThread&) (this=0x555584f4b590, thread=...) at ../libs/juce-current/source/modules/juce_core/threads/juce_ThreadPool.cpp:384
#10 0x00007fff95a70d13 in juce::ThreadPool::ThreadPoolThread::run() (this=0x555582e4ca00) at ../libs/juce-current/source/modules/juce_core/threads/juce_ThreadPool.cpp:36
#11 0x00007fff95a36821 in juce::Thread::threadEntryPoint() (this=0x555582e4ca00) at ../libs/juce-current/source/modules/juce_core/threads/juce_Thread.cpp:96
#12 0x00007fff95a368f5 in juce::juce_threadEntryPoint(void*) (userData=0x555582e4ca00) at ../libs/juce-current/source/modules/juce_core/threads/juce_Thread.cpp:118
#13 0x00007fff95a598f0 in juce::threadEntryProc(void*) (userData=0x555582e4ca00) at ../libs/juce-current/source/modules/juce_core/native/juce_posix_SharedCode.h:877
#14 0x00007ffff6915299 in start_thread () at /usr/lib/libpthread.so.0
#15 0x00007ffff6264053 in clone () at /usr/lib/libc.so.6
(gdb) 
#1  0x00007fff9675485a in juce::OpenGLShaderProgram::use (this=0x7fffb862d430) at ../libs/juce-current/source/modules/juce_opengl/opengl/juce_OpenGLShaderProgram.cpp:140
140	    context.extensions.glUseProgram (programID);
(gdb) p programID
$1 = 0
(gdb) 

```

**Comment by alex-tee** [comment]
fixed
